USE [master]
GO
/****** Object:  Database [qlsv]    Script Date: 5/28/2026 12:20:15 PM ******/
CREATE DATABASE [qlsv]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'qlsv', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\qlsv.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'qlsv_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\qlsv_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [qlsv] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [qlsv].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [qlsv] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [qlsv] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [qlsv] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [qlsv] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [qlsv] SET ARITHABORT OFF 
GO
ALTER DATABASE [qlsv] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [qlsv] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [qlsv] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [qlsv] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [qlsv] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [qlsv] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [qlsv] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [qlsv] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [qlsv] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [qlsv] SET  ENABLE_BROKER 
GO
ALTER DATABASE [qlsv] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [qlsv] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [qlsv] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [qlsv] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [qlsv] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [qlsv] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [qlsv] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [qlsv] SET RECOVERY FULL 
GO
ALTER DATABASE [qlsv] SET  MULTI_USER 
GO
ALTER DATABASE [qlsv] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [qlsv] SET DB_CHAINING OFF 
GO
ALTER DATABASE [qlsv] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [qlsv] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [qlsv] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [qlsv] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'qlsv', N'ON'
GO
ALTER DATABASE [qlsv] SET QUERY_STORE = ON
GO
ALTER DATABASE [qlsv] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [qlsv]
GO
/****** Object:  Table [dbo].[tbl_lophoc]    Script Date: 5/28/2026 12:20:15 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tbl_lophoc](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[malop] [varchar](20) NULL,
	[tenlop] [nvarchar](100) NULL,
	[ghichu] [nvarchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[malop] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tbl_sinhviens]    Script Date: 5/28/2026 12:20:15 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tbl_sinhviens](
	[id] [int] NOT NULL,
	[hoten] [nvarchar](100) NULL,
	[gioitinh] [nvarchar](10) NULL,
	[ngaysinh] [date] NULL,
	[malop] [varchar](20) NULL,
 CONSTRAINT [PK__tbl_sinh__3213E83F2A508AF7] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[tbl_sinhviens]  WITH CHECK ADD  CONSTRAINT [FK_SinhVien_LopHoc] FOREIGN KEY([malop])
REFERENCES [dbo].[tbl_lophoc] ([malop])
GO
ALTER TABLE [dbo].[tbl_sinhviens] CHECK CONSTRAINT [FK_SinhVien_LopHoc]
GO
USE [master]
GO
ALTER DATABASE [qlsv] SET  READ_WRITE 
GO
